set(
    HOPWINS_BOARD_TARGET
    "FOLLOWER_FULL"
    CACHE STRING
    "Physical PCB assembly target"
)
set_property(
    CACHE HOPWINS_BOARD_TARGET
    PROPERTY STRINGS LEADER_UWB_ONLY FOLLOWER_FULL
)

if(HOPWINS_BOARD_TARGET STREQUAL "LEADER_UWB_ONLY")
    set(HOPWINS_BOARD_TARGET_DEFINE
        HOPWINS_BOARD_TARGET_LEADER_UWB_ONLY)
    set(HOPWINS_BOARD_EMBED_FPGA_IMAGE FALSE)
    set(HOPWINS_BOARD_HAS_CLOCK_CONTROL FALSE)
elseif(HOPWINS_BOARD_TARGET STREQUAL "FOLLOWER_FULL")
    set(HOPWINS_BOARD_TARGET_DEFINE
        HOPWINS_BOARD_TARGET_FOLLOWER_FULL)
    set(HOPWINS_BOARD_EMBED_FPGA_IMAGE TRUE)
    set(HOPWINS_BOARD_HAS_CLOCK_CONTROL TRUE)
else()
    message(FATAL_ERROR
        "Unsupported HOPWINS_BOARD_TARGET: ${HOPWINS_BOARD_TARGET}")
endif()
