#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/zhang/OneDrive/Desktop/UWBDO/HopWINS-UWBDO/FPGA/impl_1}]} {
  file mkdir {C:/Users/zhang/OneDrive/Desktop/UWBDO/HopWINS-UWBDO/FPGA/impl_1}
}
cd {C:/Users/zhang/OneDrive/Desktop/UWBDO/HopWINS-UWBDO/FPGA/impl_1}

sys_set_attribute -gui on -msg {C:/Users/zhang/OneDrive/Desktop/UWBDO/HopWINS-UWBDO/FPGA/promote.xml}
msg_load {C:/Users/zhang/OneDrive/Desktop/UWBDO/HopWINS-UWBDO/FPGA/promote.xml}
des_set_project_udb -in {HopWINS_UWBDO_FPGA_impl_1_syn.udb} -out {HopWINS_UWBDO_FPGA_impl_1_map.udb} -milestone map -pm ice40tp
des_set_reference_udb -clean
map_set_option {pdc_file "C:/Users/zhang/OneDrive/Desktop/UWBDO/HopWINS-UWBDO/FPGA/source/impl_1/pin_assign.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false }
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
